---
title: Agia Academy
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
description: Agia Academy matches netrunners with rookies, and sends them on adventures
theme: jekyll-theme-cayman
show_downloads: true
