---
title: Agia Academy
description: A self-paced program for learning Web Development
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
show_downloads: true
